TP_PWEB/TP_PWEB/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_PWEB.Data;
using TP_PWEB.Models;
using TP_PWEB.ViewModels;

namespace TP_PWEB.Controllers
{
    [Authorize (Roles = "Administrator")]
    public class CompanyController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CompanyController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Company
        public async Task<IActionResult> Index(string? TextoAPesquisar, string? ordem, string? estado)
        {
            var ListaEmpresas = new List<Company>();

            var ListaOrdem = new List<SelectListItem> {
				new SelectListItem { Text = "Estado", Value = "Estado", Selected = ordem == "Estado" ? true : false },
				new SelectListItem { Text = "Classificação", Value = "Classificação" , Selected = ordem == "Classificação" ? true : false},
                new SelectListItem { Text = "Alfabética", Value = "Alfabética", Selected = ordem == "Alfabética" ? true : false }
            };

            var ListaEstados = new List<SelectListItem> {
                new SelectListItem { Text = "Todas", Value = "" , Selected = estado == "" ? true : false},
                new SelectListItem { Text = "Ativas", Value = true.ToString(), Selected = estado == "True" ? true : false },
                new SelectListItem { Text = "Inativas", Value = false.ToString(), Selected = estado == "False" ? true : false }
            };

            ViewData["ListaOrdem"] = ListaOrdem;
            ViewData["ListaEstados"] = ListaEstados;
            ViewData["TextoPesquisado"] = TextoAPesquisar;

            if (!string.IsNullOrWhiteSpace(TextoAPesquisar))
            {
                ListaEmpresas = await _context.Company.Where(c => c.Name.ToUpper().Contains(TextoAPesquisar.ToUpper())).ToListAsync();
                TextoAPesquisar = " que contêm \"" + TextoAPesquisar + "\"";
            }
            else
                ListaEmpresas = await _context.Company.ToListAsync();

            if (estado != null)
            {
                if (estado == true.ToString())
                    ViewData["Resultado"] = "Lista de Empresas Ativas" + TextoAPesquisar;
                else
                    ViewData["Resultado"] = "Lista de Empresas Inativas" + TextoAPesquisar;

                ListaEmpresas = ListaEmpresas.Where(c => c.Active == Convert.ToBoolean(estado)).ToList();
            }
            else
                ViewData["Resultado"] = "Lista de Empresas" + TextoAPesquisar;

            if (ordem == "Classificação")
                ListaEmpresas = ListaEmpresas.OrderByDescending(e => e.rating).ToList();
            else if (ordem == "Alfabética")
				ListaEmpresas = ListaEmpresas.OrderBy(e => e.Name).ToList();
			else
                ListaEmpresas = ListaEmpresas.OrderByDescending(e => e.Active).ToList();

            return View(ListaEmpresas);
        }

        // GET: Company/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Company == null)
            {
                return NotFound();
            }

            var empresa = await _context.Company.FirstOrDefaultAsync(e => e.Id == id);
            if (empresa == null)
            {
                return NotFound();
            }

            var empresaVM = new CompanyDetailsViewModel();
            var gestores = new List<ApplicationUser>();
            var funcionarios = new List<ApplicationUser>();

			var users = await _userManager.Users.OrderBy(u => u.FirstName).ToListAsync();
			foreach (ApplicationUser user in users)
            {
				if (user.CompanyID == id)
                {
                    if (await _userManager.IsInRoleAsync(user, "Manager"))
                        gestores.Add(user);
                    if (await _userManager.IsInRoleAsync(user, "Worker"))
                        funcionarios.Add(user);
				}
			}

            var total = _context.Vehicle.Where(v => v.CompanyId == id).Count();

			empresaVM.Company = empresa;
            empresaVM.TotalVehicles = total;
            empresaVM.Menagers = gestores;
            empresaVM.Workers = funcionarios;

            return View(empresaVM);
        }

        // GET: Company/Create
        public IActionResult Create()
        {
            ViewBag.ListaErros = new List<string>();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CompanyMenagerViewModel empresaVM)
        {
            var novaEmpresa = new Company
            {
                Name = empresaVM.NomeEmpresa,
                Active = empresaVM.AtivoEmpresa
            };

            ModelState.Remove(nameof(novaEmpresa.Workers));
            ModelState.Remove(nameof(novaEmpresa.Vehicles));
            if (ModelState.IsValid)
            {
                _context.Add(novaEmpresa);
                await _context.SaveChangesAsync();

                var gestor = new ApplicationUser
                {
                    UserName = empresaVM.EmailGestor,
                    Email = empresaVM.EmailGestor,
                    FirstName = empresaVM.PrimeiroNomeGestor,
                    LastName = empresaVM.UltimoNomeGestor,
                    Active = empresaVM.AtivoGestor,
                    CompanyID = novaEmpresa.Id,
                    EmailConfirmed = true
                };

                var user = await _userManager.FindByEmailAsync(gestor.Email);
                if (user == null)
                {
                    var result = await _userManager.CreateAsync(gestor, empresaVM.PasswordGestor);
                    if (result.Succeeded)
                    {
                        await _userManager.AddToRoleAsync(gestor, "Manager");
                        return RedirectToAction(nameof(Index));
                    }

                    var ListaErros = new List<string>();
                    foreach (var error in result.Errors)
                    {
                        //ModelState.AddModelError(string.Empty, error.Description);
                        ListaErros.Add(error.Description);
                    }
                    ViewBag.ListaErros = ListaErros;
                }
            }

            _context.Remove(novaEmpresa);
            await _context.SaveChangesAsync();

            return View(empresaVM);
        }

        // GET: Company/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Company == null)
            {
                return NotFound();
            }

            var empresa = await _context.Company.FindAsync(id);
            if (empresa == null)
            {
                return NotFound();
            }

            ViewBag.NomeEmpresa = empresa.Name;

            return View(empresa);
        }

        // POST: Company/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Clasyfication,Active")] Company empresa)
        {
            if (id != empresa.Id)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(empresa.rating));
            ModelState.Remove(nameof(empresa.Workers));
            ModelState.Remove(nameof(empresa.Vehicles));
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empresa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpresaExists(empresa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(empresa);
        }

        // GET: Company/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Company == null)
            {
                return NotFound();
            }

            var empresa = await _context.Company.FirstOrDefaultAsync(m => m.Id == id);
            if (empresa == null)
            {
                return NotFound();
            }

            var totalVeiculos = _context.Vehicle.Where(v => v.CompanyId == id).Count();
            if (totalVeiculos > 0)
            {
                ViewBag.PodeApagar = false;
            }
            else
            {
                ViewBag.PodeApagar = true;
            }

            return View(empresa);
        }

        // POST: Company/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Company == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Empresa'  is null.");
            }

            var empresa = await _context.Company.FindAsync(id);
            if (empresa != null)
            {
                var results = await _userManager.Users.Where(u => u.CompanyID == id).ToListAsync();

                foreach (ApplicationUser user in results)
                {

TP_PWEB/TP_PWEB/Controllers/UsersManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Runtime.Intrinsics.Arm;
using TP_PWEB.Models;
using TP_PWEB.ViewModels;

namespace TP_PWEB.Controllers
{
    [Authorize (Roles = "Administrator")]
    public class UsersManagerController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersManagerController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index(string? TextoAPesquisar, string? estado, string? cargo)
        {
			var users = new List<ApplicationUser>();

			var ListaEstados = new List<SelectListItem> {
				new SelectListItem { Text = "Todos", Value = "" , Selected = estado == "" ? true : false},
				new SelectListItem { Text = "Ativos", Value = true.ToString(), Selected = estado == "True" ? true : false },
				new SelectListItem { Text = "Inativos", Value = false.ToString(), Selected = estado == "False" ? true : false }
			};

			var ListaCargos = new List<SelectListItem> {
				new SelectListItem { Text = "Todos", Value = "Todos", Selected = cargo == "Todos" ? true : false },
				new SelectListItem { Text = "Cliente", Value = "Cliente" , Selected = cargo == "Cliente" ? true : false},
				new SelectListItem { Text = "Funcionario", Value = "Funcionario" , Selected = cargo == "Funcionario" ? true : false},
				new SelectListItem { Text = "Gestor", Value = "Gestor" , Selected = cargo == "Gestor" ? true : false},
				new SelectListItem { Text = "Administrador", Value = "Administrador", Selected = cargo == "Administrador" ? true : false }
			};

			ViewData["ListaCargos"] = ListaCargos;
			ViewData["ListaEstados"] = ListaEstados;
			ViewData["TextoPesquisado"] = TextoAPesquisar;

			if (!string.IsNullOrWhiteSpace(TextoAPesquisar))
			{
				users = _userManager.Users.Include(a => a.Company).Where(a => a.FirstName.Contains(TextoAPesquisar) 
														|| a.LastName.Contains(TextoAPesquisar)
														|| a.Email.Contains(TextoAPesquisar)).
														OrderBy(a => a.FirstName).ToList();
				TextoAPesquisar = " que contêm \"" + TextoAPesquisar + "\"";
			}
			else
				users = _userManager.Users.Include(a => a.Company).OrderBy(a => a.Company).ToList();

			if (estado != null)
			{
				if (estado == true.ToString())
					ViewData["Resultado"] = "Lista de Utilizadores Ativos" + TextoAPesquisar;
				else
					ViewData["Resultado"] = "Lista de Utilizadores Inativos" + TextoAPesquisar;

				users = users.Where(c => c.Active == Convert.ToBoolean(estado)).ToList();
			}
			else
				ViewData["Resultado"] = "Lista de Utilizadores" + TextoAPesquisar;

			if (cargo != null && cargo != "Todos")
			{
				var temp = new List<ApplicationUser>();
				foreach (ApplicationUser user in users)
				{
					if (await _userManager.IsInRoleAsync(user, cargo))
					{
						temp.Add(user);
					}
				}
				users = temp;
			}

			ViewBag.Total = users.Count;

			var userRolesViewModel = new List<UserManagerViewModel>();
            foreach (ApplicationUser user in users)
            {
                var utilizadorVM = new UserManagerViewModel();
                utilizadorVM.UserId = user.Id;
                utilizadorVM.UserName = user.UserName;
                utilizadorVM.FirstName = user.FirstName;
                utilizadorVM.LastName = user.LastName;
                utilizadorVM.Active = user.Active;
                utilizadorVM.RolesNames = await GetUserRoles(user);
                if (await _userManager.IsInRoleAsync(user, "Worker") || await _userManager.IsInRoleAsync(user, "Manager"))
                {
					if(user.Company != null) { 
						utilizadorVM.CompanyName = user.Company.Name;
					}
				}
                userRolesViewModel.Add(utilizadorVM);
            }

            return View(userRolesViewModel);
        }

        private async Task<List<string>> GetUserRoles(ApplicationUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }

		public async Task<IActionResult> Edit(string userId)
		{
			ViewBag.userId = userId;

			var user = await _userManager.FindByIdAsync(userId);

			if (user == null)
			{
				return View("Not Found");
			}

			ViewBag.UserName = user.UserName;

			var utilizadorVM = new UserManagerViewModel();
            var listaRoles = new List<RolesData>();

			foreach (var role in _roleManager.Roles)
			{
				var userRolesViewModel = new RolesData
				{
					RoleId = role.Id,
					RoleName = role.Name
				};

				if (await _userManager.IsInRoleAsync(user, role.Name))
					userRolesViewModel.Selected = true;
				else
					userRolesViewModel.Selected = false;

				listaRoles.Add(userRolesViewModel);
			}

            utilizadorVM.FirstName = user.FirstName;
            utilizadorVM.LastName = user.LastName;
            utilizadorVM.Active = user.Active;
            utilizadorVM.ListRoles = listaRoles;

            return View(utilizadorVM);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(UserManagerViewModel model, string userId)
		{
			var user = await _userManager.FindByIdAsync(userId);

			if (user == null)
			{
				return View();
			}

			user.FirstName = model.FirstName;
			user.LastName = model.LastName;
			user.Active = model.Active;

			var roles = await _userManager.GetRolesAsync(user);
			var result = await _userManager.RemoveFromRolesAsync(user, roles);

			if (!result.Succeeded)
			{
				ModelState.AddModelError("", "Cannot remove user existing roles");
				return View(model);
			}

			result = await _userManager.AddToRolesAsync(user, model.ListRoles.Where(x => x.Selected).Select(y => y.RoleName));

			if (!result.Succeeded)
			{
				ModelState.AddModelError("", "Cannot add selected roles to user");
				return View(model);
			}

			return RedirectToAction("Index");
		}
    }
}

TP_PWEB/TP_PWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TP-PWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body class="d-flex h-100 text-center  bg-white p-0 m-0">
    <div class="cover-container d-flex w-100 h-100 p-0 mx-auto flex-column">
        <header class="p-7 text-white">
            <div class="container">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark mb-3 fixed-top" style="background: rgba(0, 0, 0, .6);">
                    <div class="container">
                        <a class="navbar-brand text-warning" style="display:flex; align-items:center;" asp-area="" asp-controller="Home" asp-action="Index">
                            <strong>PWEB</strong> 
                        </a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                                @if (User.Identity.IsAuthenticated)
                                {
                                    if (User.IsInRole("Client"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="Reservation" asp-action="Index">RESERVAS</a>
                                        </li>
                                    }

                                    if (User.IsInRole("Worker") || User.IsInRole("Manager"))
                                    {
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">GERIR FROTA DE VEÍCULOS</a>
                                            <ul class="dropdown-menu">
                                                <li class="nav-item">
                                                    <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="VehicleFleetManagment" asp-action="Index">Listar Registo de Veículos</a>
                                                </li>
                                                <li>
                                                    <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="VehicleFleetManagment" asp-action="Create">Registar Veículo</a>
                                                </li>
                                            </ul>
                                        </li>

                                        if (User.IsInRole("Manager"))
                                        {
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">GERIR FUNCIONÁRIOS</a>
                                                <ul class="dropdown-menu">
                                                    <li class="nav-item">
                                                        <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="Worker" asp-action="Index">Listagem de Funcionários</a>
                                                    </li>
                                                    <li>
                                                        <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="Worker" asp-action="Create">Adicionar Funcionário</a>
                                                    </li>
                                                </ul>
                                            </li>
                                        }
                                    }

                                    if (User.IsInRole("Administrator"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="VehicleCategories" asp-action="Index">CATEGORIAS DE VEICULOS</a>
                                        </li>

                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="UsersManager" asp-action="Index">UTILIZADORES</a>
                                        </li>

                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">EMPRESAS</a>
                                            <ul class="dropdown-menu">
                                                <li class="nav-item">
                                                    <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="Company" asp-action="Index">Todas as Empresas</a>
                                                </li>
                                                <li>
                                                    <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="Company" asp-action="Create">Adicionar Empresa</a>
                                                </li>
                                            </ul>
                                        </li>
                                    }
                                }

                            </ul>
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <main class="container mt-5 pt-5 text-start">
            @RenderBody()
        </main>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; PWEB 2022/23 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TP_PWEB/TP_PWEB/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TP-PWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/carousel.css" asp-append-version="true" />
</head>
<body class="d-flex h-100 text-center  bg-white p-0 m-0">
    <div class="cover-container d-flex w-100 h-100 p-0 mx-auto flex-column">
        <header class="p-7 text-white">
            <div class="container">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark mb-3 fixed-top" style="background: rgba(0, 0, 0, .5);">
                    <div class="container">
                        <a class="navbar-brand text-warning" style="display:flex; align-items:center;" asp-area="" asp-controller="Home" asp-action="Index">
                            <strong>PWEB</strong>
                        </a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                                @if (User.Identity.IsAuthenticated)
                                {
                                    if (User.IsInRole("Client"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="Reservation" asp-action="Index">RESERVAS</a>
                                        </li>
                                    }

                                    if (User.IsInRole("Worker") || User.IsInRole("Manager"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="Reservation" asp-action="Index">RESERVAS</a>
                                        </li>

                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">GERIR FROTA DE VEÍCULOS</a>
                                            <ul class="dropdown-menu">
                                                <li class="nav-item">
                                                    <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="VehicleFleetManagment" asp-action="Index">Listar Registo de Veículos</a>
                                                </li>
                                                <li>
                                                    <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="VehicleFleetManagment" asp-action="Create">Registar Veículo</a>
                                                </li>
                                            </ul>
                                        </li>

                                        if (User.IsInRole("Manager"))
                                        {
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">GERIR FUNCIONÁRIOS</a>
                                                <ul class="dropdown-menu">
                                                    <li class="nav-item">
                                                        <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="Worker" asp-action="Index">Listagem de Funcionários</a>
                                                    </li>
                                                    <li>
                                                        <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="Worker" asp-action="Create">Adicionar Funcionário</a>
                                                    </li>
                                                </ul>
                                            </li>
                                        }
                                    }

                                    if (User.IsInRole("Administrator"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="VehicleCategories" asp-action="Index">CATEGORIAS DE VEICULOS</a>
                                        </li>

                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="UsersManager" asp-action="Index">UTILIZADORES</a>
                                        </li>

                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">EMPRESAS</a>
                                            <ul class="dropdown-menu">
                                                <li class="nav-item">
                                                    <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="Company" asp-action="Index">Todas as Empresas</a>
                                                </li>
                                                <li>
                                                    <a class="nav-link text-black btn-outline-light" asp-area="" asp-controller="Company" asp-action="Create">Adicionar Empresa</a>
                                                </li>
                                            </ul>
                                        </li>
                                    }
                                }

                            </ul>
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <main class="px-0 mx-0">
            @RenderBody()
        </main>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; PWEB 2022/23 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>