TP_PWEB/TP_PWEB/Models/VehicleCategory.cs
using System.ComponentModel.DataAnnotations;

namespace TP_PWEB.Models
{
    public class VehicleCategory
    {
        public int Id { get; set; }

        [Display(Name = "type of vehicle")]
        public string Name { get; set; }

        public ICollection<Vehicle> Vehicles { get; set; }
    }
}

TP_PWEB/TP_PWEB/Controllers/VehicleCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_PWEB.Data;
using TP_PWEB.Models;
using TP_PWEB.ViewModels;

namespace TP_PWEB.Controllers
{
    [Authorize (Roles = "Administrator")]
    public class VehicleCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VehicleCategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: VehicleCategories
        public async Task<IActionResult> Index()
        {
            var categories = await _context.VehicleCategory.ToListAsync();

            return View(categories);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCategoria(string categoryName)
        {
            if (categoryName != null)
            {
                VehicleCategory categoria = new VehicleCategory();
                categoria.Name = categoryName;

                _context.Add(categoria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction("Index");
        }

        // GET: VehicleCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VehicleCategory == null)
            {
                return NotFound();
            }

            var categoriaVeiculo = await _context.VehicleCategory.FindAsync(id);
            if (categoriaVeiculo == null)
            {
                return NotFound();
            }

            ViewBag.NomeCategoria = categoriaVeiculo.Name;

            return View(categoriaVeiculo);
        }

        // POST: VehicleCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] VehicleCategory categoriaVeiculo)
        {
            if (id != categoriaVeiculo.Id)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(categoriaVeiculo.Vehicles));
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoriaVeiculo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaVeiculoExists(categoriaVeiculo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoriaVeiculo);
        }

        // GET: VehicleDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VehicleCategory == null)
            {
                return NotFound();
            }

            var categoriaVeiculo = await _context.VehicleCategory
				.FirstOrDefaultAsync(m => m.Id == id);
            if (categoriaVeiculo == null)
            {
                return NotFound();
            }

            return View(categoriaVeiculo);
        }

        // POST: VehicleDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VehicleCategory == null)
            {
                return Problem("Entity set 'ApplicationDbContext.CategoriaVeiculo'  is null.");
            }
            var categoriaVeiculo = await _context.VehicleCategory.FindAsync(id);
            if (categoriaVeiculo != null)
            {
                _context.VehicleCategory.Remove(categoriaVeiculo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriaVeiculoExists(int id)
        {
          return _context.VehicleCategory.Any(e => e.Id == id);
        }
    }
}

TP_PWEB/TP_PWEB/Views/VehicleCategories/Delete.cshtml
@model TP_PWEB.Models.VehicleCategory

@{
    ViewData["Title"] = "Eliminar";
}

<h2>Eliminar Categoria</h2>

<h4>Tem a certeza que quer apagar a seguinte categoria de veiculos?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Remover" class="btn btn-danger" />
        <a class="btn btn-primary" asp-action="Index">Cancelar</a>
    </form>
</div>

TP_PWEB/TP_PWEB/Views/VehicleCategories/Edit.cshtml
@model TP_PWEB.Models.VehicleCategory

@{
    ViewData["Title"] = "Editar";
}

<h2>Editar categoria</h2>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="card">
        <div class="card-header">
            <h4 class="m-1"><b>@ViewBag.NomeCategoria</b></h4>
        </div>

        <div class="card-body">
            <h5>Nome</h5>
            <div class="form-group">
                <input style="width: 20em !important" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Confirmar" class="btn btn-primary"
                   style="width:auto" />
            <a asp-action="Index"
               class="btn btn-primary" style="width:auto">Cancelar</a>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TP_PWEB/TP_PWEB/Views/VehicleCategories/Index.cshtml
@model IEnumerable<TP_PWEB.Models.VehicleCategory>

@{
    ViewData["Title"] = "Gestão de Categorias";
}

<h2>Gestão de Categorias de Veiculos</h2>

<div class="row mt-3">
	<div class="col-md-4">
		<form method="post" asp-action="AddCategoria" asp-controller="VehicleCategories">
			<div class="input-group">
                <input style="margin-inline-end: .5em" name="categoryName" class="form-control">
				<span class="input-group-btn">
					<button class="btn btn-primary">Adicionar Categoria</button>
				</span>
			</div>
		</form>
	</div>
</div>

<table style="vertical-align: middle" class="table table-striped table-hover table-bordered mt-3">
    <caption style="caption-side:top">Lista de Categorias</caption>
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th style="text-align:center">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td style="text-align:center">
                    <a style="margin-inline-end: .5em" class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Remover</a>
                </td>
            </tr>
        }
    </tbody>
</table>