TP_PWEB/TP_PWEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Runtime.Intrinsics.Arm;
using TP_PWEB.Data;
using TP_PWEB.Models;
using TP_PWEB.ViewModels;

namespace TP_PWEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index(string? TextoAPesquisar, string? estado, string? categoriaId, string? empresaId, string? ordem)
        {
            var ListaOrdem = new List<SelectListItem> {
                new SelectListItem { Text = "Preço (Ascendente)", Value = "Preço (Ascendente)", Selected = ordem == "Preço (Ascendente)" ? true : false },
                new SelectListItem { Text = "Preço (Descendente)", Value = "Preço (Descendente)", Selected = ordem == "Preço (Descendente)" ? true : false },
                new SelectListItem { Text = "Classificação (Descendente)", Value = "Classificação (Descendente)", Selected = ordem == "Classificação (Descendente)" ? true : false },
                new SelectListItem { Text = "Classificação (Ascendente)", Value = "Classificação (Ascendente)", Selected = ordem == "Classificação (Ascendente)" ? true : false }
            };

            var ListaCategorias = new List<SelectListItem>
            {
                new SelectListItem { Text = "Todas", Value = "-1", Selected = categoriaId == "-1" ? true : false }
            };
            foreach (VehicleCategory cat in _context.VehicleCategory)
            {
                ListaCategorias.Add(new SelectListItem { Text = cat.Name, Value = cat.Id.ToString(), Selected = categoriaId == cat.Id.ToString() ? true : false });
            }

            var ListaEmpresas = new List<SelectListItem>
            {
                new SelectListItem { Text = "Todas", Value = "-1", Selected = empresaId == "-1" ? true : false }
            };
            foreach (Company emp in _context.Company)
            {
                ListaEmpresas.Add(new SelectListItem { Text = emp.Name, Value = emp.Id.ToString(), Selected = empresaId == emp.Id.ToString() ? true : false });
            }

            ViewData["ListaOrdem"] = ListaOrdem;
            ViewData["ListaCategorias"] = ListaCategorias;
            ViewData["ListaEmpresas"] = ListaEmpresas;
            ViewData["TextoPesquisado"] = TextoAPesquisar;

            var veiculos = await _context.Vehicle.Include(v => v.Category).Include(v => v.Company).Where(v => v.Available == true).ToListAsync();

            if (!string.IsNullOrWhiteSpace(TextoAPesquisar))
            {
                veiculos = veiculos.Where(v => v.Brand.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                            || v.Brand.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                            || v.Location.ToUpper().Contains(TextoAPesquisar.ToUpper())).ToList();
            }

            if (categoriaId != null)
            {
                int catId;
                try
                {
                    catId = int.Parse(categoriaId);
                }
                catch (FormatException)
                {
                    Console.WriteLine($"Erro a converter '{categoriaId}'");
                    return NotFound();
                }

                if (catId != -1)
                {
                    veiculos = veiculos.Where(v => v.CategoryID == catId).ToList();
                }
            }

            if (empresaId != null)
            {
                int empId;
                try
                {
                    empId = int.Parse(empresaId);
                }
                catch (FormatException)
                {
                    Console.WriteLine($"Erro a converter '{empresaId}'");
                    return NotFound();
                }

                if (empId != -1)
                {
                    veiculos = veiculos.Where(v => v.CompanyId == empId).ToList();
                }
            }

            if (ordem == "Preço (Descendente)")
                veiculos = veiculos.OrderByDescending(v => v.Price).ToList();
            else if (ordem == "Classificação (Descendente)")
                veiculos = veiculos.OrderByDescending(v => v.Company.rating).ToList();
            else if (ordem == "Classificação (Ascendente)")
                veiculos = veiculos.OrderBy(v => v.Company.rating).ToList();
            else
                veiculos = veiculos.OrderBy(v => v.Price).ToList();


            return View(veiculos);
        }

        // GET: Veiculos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var veiculo = await _context.Vehicle
                .Include(v => v.Category)
                .Include(v => v.Company)
                .Where(v => v.Available == true)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (veiculo == null)
            {
                return NotFound();
            }

            return View(veiculo);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TP_PWEB/TP_PWEB/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_PWEB.Data;
using TP_PWEB.Models;
using TP_PWEB.ViewModels;

namespace TP_PWEB.Controllers
{
    public class ReservationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ReservationController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: reservation
        [Authorize(Roles = "Client,Worker,Manager")]
        public async Task<IActionResult> Index(string? TextoAPesquisar, DateTime? dataMin, DateTime? dataMax, string? estado, string? categoriaId)
        {
            var userId = _userManager.GetUserId(User);
            var user = _context.Users.Find(userId);

            if (user == null)
            {
                return NotFound();
            }

            var reservas = new List<Reservation>();

            // worker/manager
            if (await _userManager.IsInRoleAsync(user, "Worker") || await _userManager.IsInRoleAsync(user, "Manager"))
            {
                reservas = await _context.Reservation.Include(r => r.Client).Include(r => r.PickUpWorker).Include(r => r.PickUpWorker).Include(r => r.Vehicle)
                    .Where(r => r.Vehicle.CompanyId == user.CompanyID).ToListAsync();

                var ListaEstados = new List<SelectListItem> {
                    new SelectListItem { Text = "Todas", Value = "Todas", Selected = estado == "Todas" ? true : false },
                    new SelectListItem { Text = "Rejeitadas", Value = "Rejeitadas", Selected = estado == "Rejeitadas" ? true : false },
                    new SelectListItem { Text = "Pendentes", Value = "Pendentes", Selected = estado == "Pendentes" ? true : false },
                    new SelectListItem { Text = "Aceites", Value = "Aceites", Selected = estado == "Aceites" ? true : false },
                    new SelectListItem { Text = "Encerradas", Value = "Encerradas", Selected = estado == "Encerradas" ? true : false }
                };

                var ListaCategorias = new List<SelectListItem>
                {
                    new SelectListItem { Text = "Todas", Value = "-1", Selected = categoriaId == "-1" ? true : false }
                };
                foreach (VehicleCategory cat in _context.VehicleCategory)
                {
                    ListaCategorias.Add(new SelectListItem { Text = cat.Name, Value = cat.Id.ToString(), Selected = categoriaId == cat.Id.ToString() ? true : false });
                }

                ViewData["ListaEstados"] = ListaEstados;
                ViewData["ListaCategorias"] = ListaCategorias;
                ViewData["TextoPesquisado"] = TextoAPesquisar;

                if (!string.IsNullOrWhiteSpace(TextoAPesquisar))
                {
                    reservas = reservas.Where(r => r.Vehicle.Brand.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                                || r.Vehicle.Model.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                                || r.Client.FirstName.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                                || r.Client.LastName.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                                || r.Vehicle.Location.ToUpper().Contains(TextoAPesquisar.ToUpper())).ToList();
                }

				if (estado == "Rejeitadas")
					reservas = reservas.Where(r => r.ReservationState == -1).ToList();
                else if (estado == "Pendentes")
					reservas = reservas.Where(r => r.ReservationState == 0).ToList();
                else if (estado == "Aceites")
					reservas = reservas.Where(r => r.ReservationState == 1).ToList();
                else if (estado == "Encerradas")
                    reservas = reservas.Where(r => r.ReservationState == 2).ToList();

				if (categoriaId != null)
				{
					int catId;
					try
					{
						catId = int.Parse(categoriaId);
					}
					catch (FormatException)
					{
						Console.WriteLine($"Erro a converter '{categoriaId}'");
						return NotFound();
					}

					if (catId != -1)
					{
						reservas = reservas.Where(r => r.Vehicle.CategoryID == catId).ToList();
					}
				}

                if (dataMin != null)
                    reservas = reservas.Where(r => r.PickUpDate >= dataMin).ToList();
                if (dataMax != null)
                    reservas = reservas.Where(r => r.DeliveryDate <= dataMax).ToList();

                if(dataMin != null && dataMax != null)
                    ViewData["Resultado"] = "Lista de reservas desde " + dataMin + " até " + dataMax;
                else if(dataMin != null && dataMax == null)
                    ViewData["Resultado"] = "Lista de reservas desde " + dataMin;
                else if(dataMin == null && dataMax != null)
                    ViewData["Resultado"] = "Lista de reservas até " + dataMax;
            }
			// Client
			else
			{
                reservas = await _context.Reservation.Include(r => r.Client).Include(r => r.DeliveryWorker).Include(r => r.PickUpWorker).Include(r => r.Vehicle).Include(r => r.Vehicle.Company)
                    .Where(r => r.ClientId == userId).ToListAsync();

                var ListaEstados = new List<SelectListItem> {
                    new SelectListItem { Text = "Todas", Value = "Todas", Selected = estado == "Todas" ? true : false },
                    new SelectListItem { Text = "Rejeitadas", Value = "Rejeitadas", Selected = estado == "Rejeitadas" ? true : false },
                    new SelectListItem { Text = "Pendentes", Value = "Pendentes", Selected = estado == "Pendentes" ? true : false },
                    new SelectListItem { Text = "Aceites", Value = "Aceites", Selected = estado == "Aceites" ? true : false },
                    new SelectListItem { Text = "Encerradas", Value = "Encerradas", Selected = estado == "Encerradas" ? true : false }
                };

                var ListaCategorias = new List<SelectListItem>
                {
                    new SelectListItem { Text = "Todas", Value = "-1", Selected = categoriaId == "-1" ? true : false }
                };
                foreach (VehicleCategory cat in _context.VehicleCategory)
                {
                    ListaCategorias.Add(new SelectListItem { Text = cat.Name, Value = cat.Id.ToString(), Selected = categoriaId == cat.Id.ToString() ? true : false });
                }

                ViewData["ListaEstados"] = ListaEstados;
                ViewData["ListaCategorias"] = ListaCategorias;
                ViewData["TextoPesquisado"] = TextoAPesquisar;

                if (!string.IsNullOrWhiteSpace(TextoAPesquisar))
                {
                    reservas = reservas.Where(r => r.Vehicle.Brand.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                                || r.Vehicle.Model.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                                || r.Client.FirstName.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                                || r.Client.LastName.ToUpper().Contains(TextoAPesquisar.ToUpper())
                                                || r.Vehicle.Location.ToUpper().Contains(TextoAPesquisar.ToUpper())).ToList();
                }

                if (estado == "Rejeitadas")
                    reservas = reservas.Where(r => r.ReservationState == -1).ToList();
                else if (estado == "Pendentes")
                    reservas = reservas.Where(r => r.ReservationState == 0).ToList();
                else if (estado == "Aceites")
                    reservas = reservas.Where(r => r.ReservationState == 1).ToList();
                else if (estado == "Encerradas")
                    reservas = reservas.Where(r => r.ReservationState == 2).ToList();

                if (categoriaId != null)
                {
                    int catId;
                    try
                    {
                        catId = int.Parse(categoriaId);
                    }
                    catch (FormatException)
                    {
                        Console.WriteLine($"Erro a converter '{categoriaId}'");
                        return NotFound();
                    }

                    if (catId != -1)
                    {
                        reservas = reservas.Where(r => r.Vehicle.CategoryID == catId).ToList();
                    }
                }

                if (dataMin != null)
                    reservas = reservas.Where(r => r.PickUpDate >= dataMin).ToList();
                if (dataMax != null)
                    reservas = reservas.Where(r => r.DeliveryDate <= dataMax).ToList();

                if (dataMin != null && dataMax != null)
                    ViewData["Resultado"] = "Lista de reservas desde " + dataMin + " até " + dataMax;
                else if (dataMin != null && dataMax == null)
                    ViewData["Resultado"] = "Lista de reservas desde " + dataMin;
                else if (dataMin == null && dataMax != null)
                    ViewData["Resultado"] = "Lista de reservas até " + dataMax;
            }

            return View(reservas);
        }

        // GET: reservation/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Reservation == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservation
                .Include(r => r.Client)

TP_PWEB/TP_PWEB/Views/Home/Details.cshtml
@model TP_PWEB.Models.Vehicle

@{
    ViewData["Title"] = "Detalhes do veículo";
}

<div class="card mb-3">
	<div class="card-header">
		<h4 class="m-1"><b>@Model.Brand @Model.Model</b></h4>
	</div>

    <div class="card-body">
        <h5>Categoria</h5>
        @Model.Category.Name
    </div>

    <div class="card-body">
        <h5>Detalhes</h5>
        @Model.Seats Seats
        <br />
        @Model.Kms kilometers
    </div>

    <div class="card-body">
        <h5>Localização</h5>
        @Model.Location
    </div>

    <div class="card-body">
        <h5>Empresa</h5>
        @Model.Company.Name
        (@Html.DisplayFor(modelItem => Model.Company.rating)*)
    </div>

    <div class="card-body">
        <h5>Preço</h5>
        <h6>@Model.Price € <span class="fw-light">/dia</span></h6>
    </div>

	<div class="card-footer">
		<a asp-controller="Reservation" asp-action="Create" class="btn btn-primary" asp-route-veiculoId="@Model.Id">Reservar</a>
		<a asp-action="Index" class="btn btn-primary ms-2" style="width:auto">Voltar</a>
	</div>
</div>

TP_PWEB/TP_PWEB/Views/Home/Index.cshtml
@model IEnumerable<TP_PWEB.Models.Vehicle>
@* IEnumerable<TP_PWEB.Models.Veiculo> *@
@{
    ViewData["Title"] = "PWEB";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<style>
    h6 { margin-bottom: 0px; }
</style>

<div id="carouselDestaques" class="carousel slide m-0" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active banner">
            <div class="container">
                <div class="carousel-caption">
                    <br />
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-5 pt-5 text-start">
    <form method="post">
        <div class="input-group text-black mb-4">
            <div class="container">
                <div class="row" style="display:flex; flex-wrap:nowrap; justify-content:center;">
                    <div class="col-12">
                        <div class="row mb-1 justify-content-end">
                            <div class="col-3" style="display: flex; align-items: center;">
                                <h6>Pesquisa:</h6>
                                <input class="form-control ms-1" type="text" id="TextoAPesquisar" name="TextoAPesquisar" placeholder="Veículo a pesquisar" value="@ViewData["TextoPesquisado"]">
                            </div>
                            <div class="col-3" style="display: flex; align-items: center;">
                                <h6>Empresa:</h6>
                                <select class="form-select ms-1" name="empresaId" asp-items="ViewBag.ListaEmpresas"></select>
                            </div>
                            <div class="col-3" style="display: flex; align-items: center;">
                                <h6>Categoria:</h6>
                                <select class="form-select ms-1" name="categoriaId" asp-items="ViewBag.ListaCategorias"></select>
                            </div>
                            <div class="col-3" style="display: flex; align-items: center;">
                                <h6>Ordem:</h6>
                                <select class="form-select ms-1" name="ordem" asp-items="ViewBag.ListaOrdem"></select>
                            </div>
                        </div>
                    </div>

                    <div class="col-1" style="display:contents">
                        <button type="submit" class="btn btn-default" style="padding-right:0px;">
                            <img src="img/search.png">
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <table style="vertical-align: middle" class="table table-striped table-hover mt-3">
        <thead>
            <tr>
                <th>Veículo</th>
                <th>Categoria</th>
                <th>Lugares</th>
                <th>Localização</th>
                <th>Empresa</th>
                <th>Preço</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Brand @item.Model
                    </td>
                    <td>
                        @item.Category.Name
                    </td>
                    <td>
                        @item.Seats
                    </td>
                    <td>
                        @item.Location
                    </td>
                    <td>
                        @item.Company.Name (@item.Company.rating*)
                    </td>
                    <td>
                        @item.Price €/dia
                    </td>
                    <td style="text-align:center">
                        <a class="btn btn-success" asp-action="Details" asp-route-id="@item.Id">Ver oferta</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>